services:
  _defaults:
    autoconfigure: true

  MadeYourDay\RockSolidCustomElements\InsertTag\IconInsertTag:
    arguments:
      - '@twig'
      - '@monolog.logger.contao.error'
      - '%kernel.project_dir%'
      - '%contao.web_dir%'

  MadeYourDay\RockSolidCustomElements\Migration\BasicEntitiesMigration:
    arguments:
      - '@database_connection'

  MadeYourDay\RockSolidCustomElements\Twig\TwigExtension:
    arguments:
      - '@contao.image.imagine_svg'
      - '@contao.image.studio'
