services:
  _defaults:
    autoconfigure: true

  MadeYourDay\RockSolidCustomElements\Migration\BasicEntitiesMigration:
    arguments:
      - '@database_connection'

  MadeYourDay\RockSolidCustomElements\Twig\TwigExtension: ~
