services:
  _defaults:
    autoconfigure: true

  MadeYourDay\RockSolidCustomElements\Migration\BasicEntitiesMigration:
    arguments:
      - '@database_connection'

  MadeYourDay\RockSolidCustomElements\Twig\TwigExtension:
    arguments:
      - '@contao.image.imagine_svg'
      - '@contao.image.studio'
